name: Test simple

on: push

jobs:
  dire-mickey:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Bonjour les amis ! C'est moi, Mickey ! Viens dans ma voiture et il se passera plein de superbes choses pour toi ! Veux-tu échanger des pokéboules avec moi ?"

  test-php:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@4

      - name: Installer PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Vérifier la version PHP
        run: php -v

      - name: Lancer index.php (CLI)
        run: php index.php