name: Test simple

on: push

jobs:
  dire-mickey:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Bonjour les amis ! C'est moi, Mickey ! Viens dans ma voiture et il se passera plein de superbes choses pour toi ! Veux-tu échanger des pokéboules avec moi ?"